global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent_provocateur'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 2s
    # For Linux, use the docker container network:
    # - targets: ['172.17.0.1:8001']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091', 'localhost:9091']