apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    uid: prometheus
    jsonData:
      httpMethod: GET
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: prometheus