version: '3'

services:
  graphrag-mcp-server:
    build: .
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - VECTOR_DB_URL=http://vector-db:6333
      - MAX_RESULTS=10
      - MIN_CONFIDENCE=0.5
      - TRAVERSAL_DEPTH=2
      - ENABLE_CACHE=true
      - MAX_CACHE_SIZE=1000
      - CACHE_TTL=3600
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX=100
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - vector-db
    networks:
      - graphrag-network
    restart: unless-stopped

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - vector-db-data:/qdrant/storage
    networks:
      - graphrag-network
    restart: unless-stopped

networks:
  graphrag-network:
    driver: bridge

volumes:
  vector-db-data: